### PR TITLE
qt bindings and qml player

### PR DESCRIPTION
**Pull request by amorenoc**
I believe the current player is in good shape for a merge, have a look when you have time, thanks :)
There are quite a few APIs haven't been added yet, but the basics are there.

screen shot 2015-10-02 at 02 15 00

### CODE REVIEW

**Comment by sdroege** [comment]
Looks great! :) Can you squash all the commits in the qt directory together to a single commit (like "Add Qt bindings and player")? If you have any changes elsewhere, those should be separate commits.

Also I think it would be good to have the Qt bindings and the player application separated somehow, different directories or something :)

**Comment by sdroege** [comment]
FWIW, I think for a first version having everything in one directory is ok too! Did you try this only on OSX or also on other platforms?

**Comment by amorenoc** [comment]
Just OSX so far, but I may try it on Linux when I have time. Ok I will squash the commits first. Thanks!

**Comment by sdroege** [comment]
Can you add some license foo at the top of your newly added source file (.h and .cpp is probably enough)? Similar to what the other files already have :)


It also works on Linux btw, just QML seems to have problems in general with hidpi displays.

**Comment by amorenoc** [comment]
Updated PR :+1:

**Comment by sdroege** [comment]
Great, thanks :) I'll try to get through this asap. Why do you ship your own font btw?

**Comment by amorenoc** [comment]
I am using Font Awesome for the icons, we could change that to download it from a CDN, which actually QML FontLoader supports out of the box.

**Comment by sdroege** [comment]
Then you would need internet access to use the application, bundling seems better then :) What is the license of the font?

**Comment by amorenoc** [comment]
SIL Open Font License (OFL), listed here http://www.gnu.org/licenses/license-list.html

**Comment by sdroege** [comment]
Sounds good, can you add a text file next to the font with that information? Where it is from and the license. Maybe just same filename as the font, but .txt in the end?

**Comment by sdroege** [comment]
Thanks, merged!

**Pull request closed without merging**
