### PR TITLE
Extract online media into plist

### PR DESCRIPTION
**Pull request by jberkel**

### CODE REVIEW

**Comment by sdroege** [comment]
Thanks, looks good to me. I'll merge it later, but probably should also check if all the URLs are still valid :)

**Comment by jberkel** [comment]
the ogg url actually does work, but it crashes on play:
```
2015-04-22 16:44:05.311 GstPlay[62552:747360] *** Assertion failure in -[NSLayoutConstraint _setSymbolicConstant:constant:], /SourceCache/Foundation_Sim/Foundation-1144.17/Layout.subproj/NSLayoutConstraint.m:585
2015-04-22 16:44:05.315 GstPlay[62552:747360] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Constant is not finite!  That's illegal.  constant:nan'
*** First throw call stack:
(
	0   CoreFoundation                      0x0318c746 __exceptionPreprocess + 182
	1   libobjc.A.dylib                     0x05c0da97 objc_exception_throw + 44
	2   CoreFoundation                      0x0318c5da +[NSException raise:format:arguments:] + 138
	3   Foundation                          0x03602720 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 118
	4   Foundation                          0x0356de1f -[NSLayoutConstraint _setSymbolicConstant:constant:] + 171
	5   Foundation                          0x0356f342 -[NSLayoutConstraint setConstant:] + 52
	6   GstPlay                             0x00005510 -[VideoViewController viewDidLayoutSubviews] + 576
	7   GstPlay                             0x000059cc -[VideoViewController videoDimensionsChanged:height:] + 92
	8   GstPlay                             0x00005f1b __video_dimensions_changed_block_invoke + 59
	9   libdispatch.dylib                   0x05f12d8a _dispatch_call_block_and_release + 15
	10  libdispatch.dylib                   0x05f2fecf _dispatch_client_callout + 14
	11  libdispatch.dylib                   0x05f18ee3 _dispatch_main_queue_callback_4CF + 677
	12  CoreFoundation                      0x030e58ee __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14
	13  CoreFoundation                      0x030a35f0 __CFRunLoopRun + 2256
	14  CoreFoundation                      0x030a2a5b CFRunLoopRunSpecific + 443
	15  CoreFoundation                      0x030a288b CFRunLoopRunInMode + 123
	16  GraphicsServices                    0x079712c9 GSEventRunModal + 192
	17  GraphicsServices                    0x07971106 GSEventRun + 104
	18  UIKit                               0x04a30106 UIApplicationMain + 1526
	19  GstPlay                             0x0000606e main + 142
	20  libdyld.dylib                       0x05f55ac9 start + 1
	21  ???                                 0x00000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by sdroege** [comment]
Ah, we're passing some invalid value there then. What exactly is the width/height here and how does end up being NaN? 0/0?

**Comment by jberkel** [comment]
don't know, haven't debugged it. can take a look later if you want. i tried with another ogg url and it worked there.

**Comment by sdroege** [comment]
That would be great, otherwise I'll look at it when I get to it. It should be something silly in the iOS app, but once we have proper media information (pull request pending), the video-size-changed signal will probably disappear anyway.

**Comment by sdroege** [comment]
Merged :)

**Pull request closed without merging**
