### PR TITLE
remove unused variable

### PR DESCRIPTION
**Pull request by amorenoc**

### CODE REVIEW

**Comment by sdroege** [comment]
Thanks, merged :)

How's your progress with the Qt player? Anything new there?

**Comment by amorenoc** [comment]
I started last weekend to implement the new interfaces, very likely will have something this weekend.

**Comment by amorenoc** [comment]
@sdroege added new interfaces, but having some problems. One the main problems is that I can't find/use the new qml sink, at least not directly from release 1.5.90. Checking the code looks to me that headers aren't installed, and can't use the QuickItem there.

**Comment by sdroege** [comment]
Yes we don't build the Qt sink with the binaries at this point because Qt is huge. You would have to build it yourself from source

**Pull request closed without merging**
