### PR TITLE
gtk-play: add media information window 

### PR DESCRIPTION
**Pull request by codomania**
Version 1.0:

* add media information window
* update the player title to stream title

### CODE REVIEW

**Comment by sdroege** [comment]
Looks good, but it crashes for me on every video I tried. Backtrace here: https://gist.github.com/sdroege/a2d75d5859466e0416f0
Note the type and label in stack frame 6. I didn't look closer yet

**Comment by sdroege** [comment]
On audio-only files it seems to work without crashes, but there are many g_criticals() when closing it

**Comment by codomania** [comment]
Will take a look thanks. I tried couple of video and it worked for me. Does
those video work okay with gst-play?

**Comment by codomania** [comment]
There was one case which could cause failure, please try the above patch and let me know if it works for you ? I tried some media from http://samplemedia.linaro.org/H264/ and they seem to work okay (with assertion or fault) .

**Comment by sdroege** [comment]
Works, thanks :) I'll merge it in a bit.

If there is no codec tag, you could use gst_pb_utils_get_codec_description() on the caps. Also there's GST_TAG_CONTAINER_FORMAT, GST_TAG_AUDIO_CODEC, GST_TAG_VIDEO_CODEC, GST_TAG_SUBTITLE_CODEC. Maybe we should have some char* codec (and container format) description in GstPlayerMediaInfo / GstPlayerStreamInfo instead of letting the app do that?

**Comment by codomania** [comment]
Let me add api in player to get title, codec etc info then will use those
in player. Drop this patch for now.

**Comment by sdroege** [comment]
Ok. Also note that you can just update pull requests, you don't have to create new ones.

For that just push new commits to the branch you used to create the pull request. Also feel free to squash together, reorder, drop commits as needed (i.e. push --force the changes after rebase, etc).

**Comment by codomania** [comment]
okay regarding making transfer none. I was thinking to do that but one question came to mind. if media has more than one stream, is it possible to have different title name for each track ?

**Comment by sdroege** [comment]
Yes

**Comment by codomania** [comment]
so if we have more than one title in the stream, which title should we return from gst_player_media_info_get_title () ?  For now my approach was simple, I just return the title from from first available stream.

**Comment by sdroege** [comment]
For tags we should also handle the TAG message, and in there we can get told if the taglist is of global scope or not. These tags are the ones that should go into the GstPlayerMediaInfo.

For the title, you could probably do some heuristic there. If it's not in the GstPlayerMediaInfo tags, you get the one from the first video stream you find that has a title, and if no video from the first audio stream.


Maybe split the title part from the codec name part. It's a completely different story :)

**Comment by codomania** [comment]
yes make sense :) lets handle title in different commit.

**Comment by codomania** [comment]
updated with your review feedback.

**Comment by codomania** [comment]
okay let me update the API name .. and fix typo

**Comment by codomania** [comment]
updated the patch.

**Comment by sdroege** [comment]
Thanks, merged :)

**Pull request closed without merging**
