### PR TITLE
gtk-play: remove unused variables

### PR DESCRIPTION
**Pull request by ceyusa**
hihihi :)

### CODE REVIEW

**Comment by sdroege** [comment]
Thanks :) Why doesn't clang complain about those?!

**Comment by ceyusa** [comment]
> Thanks :) Why doesn't clang complain about those?!

I use clang, and it complains a lot  :)

**Comment by sdroege** [comment]
Why does *my* clang not complain about it :) 3.6.1 btw, what are you using?

**Comment by ceyusa** [comment]
> Why does my clang not complain about it :) 3.6.1 btw, what are you using?

Debian clang version 3.5.2-1 (tags/RELEASE_352/final) (based on LLVM 3.5.2)

The one that debian-testing distributes.

**Comment by sdroege** [comment]
Thanks, I'll try downgrading next time :)

**Pull request closed without merging**
